### ISSUE TITLE
Mobile touch scroll snap is jittery

### ISSUE THREAD

**Issue by shba007** [kazijawad/react-use-scroll-snap#5]
Hi I am using react-use-scroll-snap it works fine but when I Switch to mobile touch scroll the snap is very jittery. Can you fix it. There is a another library [scroll-snap](https://github.com/lucafalasco/scroll-snap) is works great in mobile. Thank you for listening

**Comment by kazijawad** [comment]
Hi, could you provide a code example of the issue, so I could see how the bug is being produced?

**Comment by shba007** [comment]
I am in using Windows 10 Node 16.16.0
![package json](https://user-images.githubusercontent.com/48382105/180682844-ea280e19-70ca-4ac3-b183-b5332336a63b.jpg)
![index css](https://user-images.githubusercontent.com/48382105/180682859-29d8edaa-c388-4fb4-8234-d7c47ec1cf91.jpg)
![Index js](https://user-images.githubusercontent.com/48382105/180682872-b5147add-e0dc-4bcc-b538-78ca27252f04.jpg)
![Landing js](https://user-images.githubusercontent.com/48382105/180682906-3c246ae1-d6cb-4cf9-9008-f7be3fc88466.jpg)
![Location js](https://user-images.githubusercontent.com/48382105/180682912-acda5f6c-46f4-4591-a750-b034d6a2930d.jpg)


https://user-images.githubusercontent.com/48382105/180682998-6e1ed937-4135-41a1-be8e-5a3a9d468d3a.mp4

**Comment by shba007** [comment]
Sorry for not able to share the whole project because it is a proprietary website. Thank you for understanding

**Comment by VRSEN** [comment]
#6 should fix it

**Comment by kazijawad** [comment]
The Hook logic has been redone and I've tested on my mobile phone. I don't see any jittery, but feel free to open a new issue with a reproducible example on the new version.

**Comment by xyba1337** [comment]
@kazijawad This is still/again a thing, been following this guide [https://dev.to/biomathcode/create-tik-tokyoutube-shorts-like-snap-infinite-scroll-react-1mca](url), everything works okey on pc but once I go to my website with my phone it's extremely jittery and buggy.
