### ISSUE TITLE
[Question] How to manually trigger the next scroll?

### ISSUE THREAD

**Issue by rvanbaalen** [kazijawad/react-use-scroll-snap#7]
I'm using react-use-scroll-snap but I want to be able to manually trigger the scroll to the next element (for instance when a user clicks a down arrow).

What's the best way to do that?

**Comment by kazijawad** [comment]
This library currently doesn't support that feature, we would need to update the library to include an optional prop that would trigger the scroll.

**Comment by rvanbaalen** [comment]
Thanks for the quick answer. I guess there's no alternative/unofficial way of doing so?

I'll close this issue for now :-)

**Comment by kazijawad** [comment]
I've reworked the Hook and exposed a new `goto` function that will let you jump to a specific index. Hopefully that will solve your issue.
